// <auto-generated />
using System;
using FarmCentralApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmCentralApp.Migrations
{
    [DbContext(typeof(FarmCentralContext))]
    partial class FarmCentralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FarmCentralApp.Models.Employee", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("AdminId")
                        .HasName("PK__Employee__59AF14B517A630CE");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("FarmCentralApp.Models.Farmer", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FARMER_ID");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FARMER_NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("FarmerId");

                    b.ToTable("Farmer");
                });

            modelBuilder.Entity("FarmCentralApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FarmerId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FARMER_ID");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("date")
                        .HasColumnName("PRODUCT_DATE");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_PRICE");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_QUANTITY");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PRODUCT_TYPE");

                    b.HasKey("ProductId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FarmCentralApp.Models.Product", b =>
                {
                    b.HasOne("FarmCentralApp.Models.Farmer", "Farmer")
                        .WithMany("Products")
                        .HasForeignKey("FarmerId")
                        .HasConstraintName("FK__Products__FARMER__3B75D760");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmCentralApp.Models.Farmer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
